//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatasetInfo", Namespace="http://schemas.datacontract.org/2004/07/Host")]
    [System.SerializableAttribute()]
    public partial struct DatasetInfo : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, int> ClassDistributionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ColumnNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowsNumberField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, int> ClassDistribution {
            get {
                return this.ClassDistributionField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassDistributionField, value) != true)) {
                    this.ClassDistributionField = value;
                    this.RaisePropertyChanged("ClassDistribution");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ColumnNumber {
            get {
                return this.ColumnNumberField;
            }
            set {
                if ((this.ColumnNumberField.Equals(value) != true)) {
                    this.ColumnNumberField = value;
                    this.RaisePropertyChanged("ColumnNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowsNumber {
            get {
                return this.RowsNumberField;
            }
            set {
                if ((this.RowsNumberField.Equals(value) != true)) {
                    this.RowsNumberField = value;
                    this.RaisePropertyChanged("RowsNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IStringService")]
    public interface IStringService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringService/DefineClass", ReplyAction="http://tempuri.org/IStringService/DefineClassResponse")]
        string DefineClass(string unknownDataset);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringService/DefineClass", ReplyAction="http://tempuri.org/IStringService/DefineClassResponse")]
        System.Threading.Tasks.Task<string> DefineClassAsync(string unknownDataset);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringService/AddString", ReplyAction="http://tempuri.org/IStringService/AddStringResponse")]
        string AddString(string knownDataset);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringService/AddString", ReplyAction="http://tempuri.org/IStringService/AddStringResponse")]
        System.Threading.Tasks.Task<string> AddStringAsync(string knownDataset);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringService/GetDatasetInformation", ReplyAction="http://tempuri.org/IStringService/GetDatasetInformationResponse")]
        Client.ServiceReference1.DatasetInfo GetDatasetInformation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringService/GetDatasetInformation", ReplyAction="http://tempuri.org/IStringService/GetDatasetInformationResponse")]
        System.Threading.Tasks.Task<Client.ServiceReference1.DatasetInfo> GetDatasetInformationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringService/GetPrivateInformation", ReplyAction="http://tempuri.org/IStringService/GetPrivateInformationResponse")]
        string GetPrivateInformation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringService/GetPrivateInformation", ReplyAction="http://tempuri.org/IStringService/GetPrivateInformationResponse")]
        System.Threading.Tasks.Task<string> GetPrivateInformationAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStringServiceChannel : Client.ServiceReference1.IStringService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StringServiceClient : System.ServiceModel.ClientBase<Client.ServiceReference1.IStringService>, Client.ServiceReference1.IStringService {
        
        public StringServiceClient() {
        }
        
        public StringServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StringServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StringServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StringServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string DefineClass(string unknownDataset) {
            return base.Channel.DefineClass(unknownDataset);
        }
        
        public System.Threading.Tasks.Task<string> DefineClassAsync(string unknownDataset) {
            return base.Channel.DefineClassAsync(unknownDataset);
        }
        
        public string AddString(string knownDataset) {
            return base.Channel.AddString(knownDataset);
        }
        
        public System.Threading.Tasks.Task<string> AddStringAsync(string knownDataset) {
            return base.Channel.AddStringAsync(knownDataset);
        }
        
        public Client.ServiceReference1.DatasetInfo GetDatasetInformation() {
            return base.Channel.GetDatasetInformation();
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.DatasetInfo> GetDatasetInformationAsync() {
            return base.Channel.GetDatasetInformationAsync();
        }
        
        public string GetPrivateInformation() {
            return base.Channel.GetPrivateInformation();
        }
        
        public System.Threading.Tasks.Task<string> GetPrivateInformationAsync() {
            return base.Channel.GetPrivateInformationAsync();
        }
    }
}
